USE Biblioteca;

INSERT INTO Exemplar (Quantidade, LivroID, BibliotecaID, Disponivel, Situacao) VALUES 
(5, 1, 1, TRUE, 'Bom estado'),
(3, 2, 1, TRUE, 'Mal estado'),
(2, 3, 2, TRUE, 'Reformado'),
(4, 1, 2, TRUE, 'Bom estado'),
(1, 2, 2, TRUE, 'Mal estado'),
(6, 3, 1, TRUE, 'Reformado'),
(2, 1, 1, TRUE, 'Bom estado'),
(3, 2, 1, TRUE, 'Mal estado'),
(4, 3, 2, TRUE, 'Reformado'),
(5, 1, 2, TRUE, 'Bom estado'),
(1, 2, 2, TRUE, 'Mal estado'),
(2, 3, 1, TRUE, 'Reformado'),
(3, 1, 1, TRUE, 'Bom estado'),
(4, 2, 1, TRUE, 'Mal estado'),
(5, 3, 2, TRUE, 'Reformado'),
(6, 1, 2, TRUE, 'Bom estado'),
(2, 2, 2, TRUE, 'Mal estado'),
(3, 3, 1, TRUE, 'Reformado'),
(4, 1, 1, TRUE, 'Bom estado'),
(5, 2, 1, TRUE, 'Mal estado'),
(1, 3, 2, TRUE, 'Reformado'),
(2, 1, 2, TRUE, 'Bom estado'),
(3, 2, 2, TRUE, 'Mal estado'),
(4, 3, 1, TRUE, 'Reformado'),
(5, 1, 1, TRUE, 'Bom estado'),
(6, 2, 1, TRUE, 'Mal estado'),
(2, 3, 2, TRUE, 'Reformado'),
(3, 1, 2, TRUE, 'Bom estado'),
(4, 2, 2, TRUE, 'Mal estado'),
(5, 3, 1, TRUE, 'Reformado');